### PR TITLE
Company name in user profile

### PR DESCRIPTION
**Pull request by palmiak**
PR based on https://wordpress.org/support/topic/adding-company-info/

### CODE REVIEW

**Comment by palmiak** [comment]
Hi is everything okay with this PR or should I fix something

**Comment by palmiak** [comment]
Hi, would it be a problem to add my login (palmiak) to contributors in a plugin? If not, no problem 😀

**Comment by arbet** [comment]
@palmiak - I would be happy to add you if you develop more complex stuff. However, if I added everyone who changed a couple of lines of code the list would get big quite fast. Hope you understand. :)

**Comment by palmiak** [comment]
No problem, just wanted to ask. Thanks

śr., 29 sie 2018, 15:48 użytkownik Samer Bechara <notifications@github.com>
napisał:

**Pull request merged**
